name: CD

on:
  push:
    branches: [main, publish]

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: npm

    steps:
      - name: Git checkout
        uses: actions/checkout@master
      - name: Install pnpm
        uses: pnpm/action-setup@v2.1.0
        with:
          version: 8.10.0
      - name: 'Publish to the npm registry'
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
      - run: pnpm install --frozen-lockfile
      - run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
